# Generated by Django 5.0.6 on 2024-07-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudl', '0002_coursesmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mudl.coursesmodule'),
        ),
    ]
